version: '3.8'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - DB_DATABASE=capstone_nodejs
      - MYSQL_ROOT_PASSWORD=1234
    env_file:
      - .env
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network

  nest-api:
    container_name: nest-api
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysql_db
      - DB_DATABASE=capstone_nodejs
      - DB_USER=root
      - DB_PASS=1234
      - DB_PORT=3306
      - DB_DIALECT=mysql
    depends_on:
      - mysql_db
    env_file: .env
    networks:
      - node-network

volumes:
  mysql_db:
    driver: local
networks:
  node-network:
